"use client";
import Layout from "./layout";
import BlurText from "@/components/BlurText";

function FeatureCard({ title, description, icon }) {
  return (
    <div className="px-6 py-8 rounded-3xl bg-gradient-to-br from-white/5 via-transparent to-black/20 border border-white/10 shadow-2xl shadow-black/50 drop-shadow-2xl backdrop-blur-xl flex flex-col items-center justify-between text-xl font-bold hover:bg-black/50 transition cursor-default max-w-sm mx-auto ">
      <div className="text-5xl mb-6">{icon}</div>
      <h3 className="text-3xl font-semibold mb-8">{title}</h3>
      <p className="text-base leading-relaxed">{description}</p>
    </div>
  );
}

export default function HomePage() {
  return (
    <Layout>
      <section className="max-w-5xl mx-auto text-center flex flex-col items-center justify-center">
        <div>
          <BlurText
            text="Welcome to Business Analyzer"
            delay={100}
            animateBy="words"
            direction="top"
            className="text-5xl font-extrabold mb-5 m-7 tracking-tight drop-shadow-lg "
          />
          <p className="text-xl max-w-3xl mx-auto mb-12 leading-relaxed drop-shadow-md ">
            "Turn your business data into your smartest advisor. Harness the
            magic of AI to reveal hidden insights, predict tomorrow’s trends,
            and power decisions that accelerate your growth. No more guesswork —
            just clear visuals, instant analysis, and real-time action plans
            tailored to you. Join thousands of innovators transforming data
            overwhelm into unstoppable success. Ready to see your business in a
            whole new light? **Dive in now and unlock the future inside your
            numbers.**"
          </p>
          <div className="space-x-8 mb-6">
            <a
              href="/login"
              className="inline-block bg-white/90 text-black font-semibold px-10 py-4 rounded-xl shadow-lg hover:bg-white transition"
            >
              Login
            </a>
            <a
              href="/login"
              className="inline-block bg-white/90 text-black font-semibold px-10 py-4 rounded-xl shadow-lg hover:bg-white transition"
            >
              Sign Up
            </a>
          </div>
        </div>
      </section>

      <section className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-16 px-6 mt-20">
        <FeatureCard
          title="AI-Powered Insights"
          description="Get instant business intelligence generated by advanced AI models to drive your growth."
          icon="🤖"
        />
        <FeatureCard
          title="Interactive Dashboards"
          description="Visualize your key metrics with customizable and easy-to-understand dashboards."
          icon="📊"
        />
        <FeatureCard
          title="Data-Driven Growth"
          description="Uncover opportunities and mitigate risks with predictive analytics tailored for your business."
          icon="🚀"
        />
      </section>
    </Layout>
  );
}
