"use client";
import Layout from "./layout";

function FeatureCard({ title, description, icon }) {
  return (
    <div className="px-6 py-8 rounded-3xl bg-[#00ADB5] border border-white/20 shadow-xl backdrop-blur-md ring-1 ring-black/30 flex flex-col items-center justify-between text-white text-xl font-bold hover:bg-[#00ADB5]/80 transition cursor-default max-w-sm mx-auto">
      <div className="text-5xl mb-6">{icon}</div>
      <h3 className="text-3xl font-semibold mb-8">{title}</h3>
      <p className="text-base leading-relaxed">{description}</p>
    </div>
  );
}

export default function HomePage() {
  return (
    <Layout>
      <section className="max-w-5xl mx-auto text-center">
        <h1 className="text-6xl font-extrabold mb-8 tracking-tight drop-shadow-lg">
          Welcome to Business Analyzer
        </h1>
        <p className="text-xl max-w-3xl mx-auto mb-12 leading-relaxed drop-shadow-md">
          Make smarter business decisions by leveraging AI-powered insights and
          comprehensive analytics dashboards. Sign up to unlock your data’s full
          potential.
        </p>
        <div className="space-x-8 mb-20">
          <a
            href="/login"
            className="inline-block bg-[#00ADB5] text-white font-semibold px-10 py-4 rounded-xl shadow-lg hover:bg-[#00ADB5]/80 transition"
          >
            Login
          </a>
          <a
            href="/login"
            className="inline-block bg-[#00ADB5] text-white font-semibold px-10 py-4 rounded-xl shadow-lg hover:bg-[#00ADB5]/80 hover:text-white transition"
          >
            Sign Up
          </a>
        </div>
      </section>

      <section className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-16 px-6">
        <FeatureCard
          title="AI-Powered Insights"
          description="Get instant business intelligence generated by advanced AI models to drive your growth."
          icon="🤖"
        />
        <FeatureCard
          title="Interactive Dashboards"
          description="Visualize your key metrics with customizable and easy-to-understand dashboards."
          icon="📊"
        />
        <FeatureCard
          title="Data-Driven Growth"
          description="Uncover opportunities and mitigate risks with predictive analytics tailored for your business."
          icon="🚀"
        />
      </section>
    </Layout>
  );
}
